version: 2


jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout:
      - run:
          name: install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'     
      - run:
          name: run test
          command: 'make test'


